2022-09-09 09:52:10 - INFO - Training/evaluation parameters: Namespace(adam_eps=1e-06, adam_lr=5e-05, base_url='../data/tnews_public/', bert_cache='../config/chinese-roberta-wwm-ext', bert_dim=768, bert_dir='hfl/chinese-roberta-wwm-ext', bert_max_length=512, bert_padding='max_length', best_score=0.5, ckpt_file='save/BD/v13/model_.bin', data_path='../data/Toursim3.csv', device='cuda', dropout=0.1, log_file='log/BD/v13.log', lstm_batch_first=True, lstm_bidirectional=True, lstm_dropout=0.0, lstm_hidden_size=256, lstm_input_size=768, lstm_num_layers=2, lstm_reflector_size=256, max_epochs=10, max_steps=50000, n_gpu=1, num_class=3, num_workers=6, prefetch=12, print_steps=10, savedmodel_path='save/BD/v13', seed=2021, smoothing=0.0, stopWords='../stopword/hit_stopwords.txt', train_batch_size=12, val_batch_size=12, val_ratio=0.2, warmup_steps=1000, weight_decay=0.001, word2Vec='../word2vec/sgns.weibo.bigram-char.bz2', word2Vec_dim=300)
Some weights of the model checkpoint at hfl/chinese-roberta-wwm-ext were not used when initializing BertModel: ['cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
2022-09-09 09:56:59 - INFO - Epoch 0 step 464: loss 0.435, {'accuracy': 0.8228, 'f1': 0.81, 'precision': 0.8136, 'recall': 0.8228}
2022-09-09 10:01:35 - INFO - Epoch 1 step 928: loss 0.450, {'accuracy': 0.8228, 'f1': 0.8065, 'precision': 0.8147, 'recall': 0.8228}
2022-09-09 10:06:10 - INFO - Epoch 2 step 1392: loss 0.463, {'accuracy': 0.8156, 'f1': 0.8145, 'precision': 0.8141, 'recall': 0.8156}
2022-09-09 10:10:46 - INFO - Epoch 3 step 1856: loss 0.510, {'accuracy': 0.8178, 'f1': 0.8072, 'precision': 0.8075, 'recall': 0.8178}
2022-09-09 10:15:22 - INFO - Epoch 4 step 2320: loss 0.551, {'accuracy': 0.8113, 'f1': 0.8026, 'precision': 0.8022, 'recall': 0.8113}
2022-09-09 10:19:59 - INFO - Epoch 5 step 2784: loss 0.709, {'accuracy': 0.8042, 'f1': 0.8038, 'precision': 0.804, 'recall': 0.8042}
Traceback (most recent call last):
  File "main.py", line 106, in <module>
  File "main.py", line 103, in main
  File "main.py", line 78, in train_and_validate
    # f1 = results['f1']
  File "main.py", line 20, in validate
    predictions.extend(pred_label_id.cpu().numpy())
KeyboardInterrupt
